//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_BDPeluqueria.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPeluqueriaEntities1 : DbContext
    {
        public BDPeluqueriaEntities1()
            : base("name=BDPeluqueriaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casa_Comerc> Casa_Comerc { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Peluquero> Peluqueros { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Res_Prod> Res_Prod { get; set; }
        public virtual DbSet<Reserva> Reservas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
