//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplicacion_BDPeluqueria.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Res_Prod
    {
        public string num_Res { get; set; }
        public string id_Prod { get; set; }
        public string cantidad { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Reserva Reserva { get; set; }
    }
}
